### PR TITLE
fix: player controls

### LINKED ISSUE #92: a click/tap on the screen that is quick with no dragging should pause/play.
After the control bar hides itself and there is no way to bring it back up, we need to make taps on the video element register correctly.

EDIT: This issue is actually a bit different. Basically we can bring the control bar back but its very hard with orbit controls how they are. I think we need to make short taps and click pause the video element as  expected.

### PR DESCRIPTION
**Pull request by BrandonOCasey**
Fixes #92

Right now its now a lot of the default player behaviors are overridden by the other controls. This pr brings them back and makes them work how we would expect.

1. A click/tap with no movement (ie not moving around the scene) should toggle playback
2. When moving around the scene the control bar should not come up. It should only come up when playback is toggled or the control bar is moved over/clicked.
3. The context menu from `right click` should show up.

### CODE REVIEW

File: scripts/rollup-replace.js [hunk 1]
```diff
@@ -39,6 +39,11 @@ export default function(options) {
 
             code = globalReplace(code, 'rotateLeft', 'scope.rotateLeft');
             code = globalReplace(code, 'rotateUp', 'scope.rotateUp');
+            // comment out the context menu prevent default line...
+            code = globalReplace(code,
+              "scope.domElement.addEventListener\\( 'contextmenu'",
```
Comment (BrandonOCasey) [inline scripts/rollup-replace.js]: This comments out https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js#L226 so that we don't preventDefault on the contextmenu. It makes sense to do this if you are using pan controls with right click, but we are not.

**Comment by ishita12** [comment]
QA LGTM

File: src/canvas-player-controls.js [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+    if (this.player.paused()) {
+      this.player.play();
+    } else {
+      this.player.pause();
+    }
+  }
+
+  onMoveStart(e) {
+
+    // if the player does not have a controlbar or
```
Comment (gkatsev) [inline src/canvas-player-controls.js]: Can this use Video.js's `tap` event?

File: src/canvas-player-controls.js [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+      'touchstart',
+      'touchmove',
+      'touchend'
+    ], this.onControlBarMove);
+
+    // we have to override these here because
+    // video.js listens for user activity on the video element
+    // and makes the user active when the mouse moves.
+    // We don't want that for 3d videos
+    this.oldReportUserActivity = this.player.reportUserActivity;
```
Comment (gkatsev) [inline src/canvas-player-controls.js]: not a huge fan of these but I don't think there's currently a way to disable it. Maybe we should have one?
Though, I guess this is also fairly self-contained and restores it on dispose.

File: src/plugin.js [hunk 4]
```diff
@@ -497,7 +498,9 @@ class VR extends Plugin {
             canvas: this.renderedCanvas,
             orientation: videojs.browser.IS_IOS || videojs.browser.IS_ANDROID || false
           });
+          this.canvasPlayerControls = new CanvasPlayerControls(this.player_, this.renderedCanvas);
```
Comment (gkatsev) [inline src/plugin.js]: should we add this as a child of the player rather than just instantiating it here?

Comment (gkatsev) [reply src/plugin.js]: oh, it's not a real component, just an object.

File: src/canvas-player-controls.js (hunk 3 above)
Comment (BrandonOCasey) [reply src/canvas-player-controls.js]: Yeah I thought about adding one, but it seems like this plugin would be the only use case.

File: src/canvas-player-controls.js (hunk 2 above)
Comment (BrandonOCasey) [reply src/canvas-player-controls.js]: let me see if that works, looks like its probably a better solution.

Comment (BrandonOCasey) [reply src/canvas-player-controls.js]: OK so I think that it would be too large of a refactor to convert this to a component and use the tap event. I think this will have to happen in another pr.

Comment (gkatsev) [reply src/canvas-player-controls.js]: sounds good.
