### PR TITLE
Fix/style override

### LINKED ISSUE #13: Allow videos to be started in cardboard mode

### PR DESCRIPTION
**Pull request by BrandonOCasey**
fix: weird camera aspect ratio stretching
fix: pixelation issues on some devices 
fix: allow the player to start in cardboard mode
fix: psudo fullscreen on iOS

Fixes #13 
Based on #15

### CODE REVIEW

File: src/cardboard-button.js [hunk 1]
```diff
@@ -46,14 +48,25 @@ class CardboardButton extends Button {
...
   }
 
+  handleOrientationChange_() {
+    if (this.active_ && videojs.browser.IS_IOS) {
+      this.changeSize_();
+    }
+  }
+
+  changeSize_() {
+    this.player_.width(window.innerWidth);
```
Comment (BrandonOCasey) [inline src/cardboard-button.js]: The window size changes during orientation when we are pseudo fullscreen on iOS

File: src/plugin.js [hunk 2]
```diff
@@ -500,8 +481,34 @@ class VR extends Plugin {
...
+        // reset the timer
+        if (timeout) {
+          window.clearTimeout(timeout);
+        }
+        timeout = window.setTimeout(() => fn.apply(undefined, args), wait);
+      };
+    };
+    // we use this to stop webvr-polyfill from making the canvas take up more
+    // space then the video element
+    const setInherit = debounce((mut) => {
```
Comment (BrandonOCasey) [inline src/plugin.js]: A hacky work-around for webvr-polyfills canvas style changes that we don't want.
